[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
# NOTE: The path is relative to the workspace ROOT
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
