[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
# ESPFLASH v2: runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# NOTE: The path is relative to the workspace ROOT
ESP_IDF_SDKCONFIG_DEFAULTS = "crates/app/sdkconfig.defaults"
