# Must be in the workspace root .... <https://github.com/esp-rs/esp-idf-sys/issues/279>
[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_SYS_ROOT_CRATE = "app"
ESP_IDF_VERSION = "v5.2.1"
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
